apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "inbox-whisperer.fullname" . }}-backend
  labels:
    {{- include "inbox-whisperer.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.commonAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
        {{- include "inbox-whisperer.labels" . | nindent 8 }}
      annotations:
        {{- with .Values.commonAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
        - name: backend
          image: {{ .Values.backend.image }}
          imagePullPolicy: {{ .Values.backend.imagePullPolicy | default "IfNotPresent" }}
          ports:
            - containerPort: 8080
          env:
            - name: ENV
              value: dev
            - name: CONFIG_FILE
              value: {{ .Values.backend.configMountPath }}
          {{- with .Values.backend.extraEnv }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
          {{- with .Values.backend.extraEnvFrom }}
          envFrom:
          {{- toYaml . | nindent 10 }}
          {{- end }}
          volumeMounts:
            - name: config
              mountPath: {{ .Values.backend.configMountPath }}
              subPath: config.json
          {{- with .Values.backend.extraVolumeMounts }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}
          livenessProbe:
            {{- toYaml .Values.backend.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.backend.readinessProbe | nindent 12 }}
      volumes:
        - name: config
          secret:
            secretName: {{ .Values.backend.configSecretName }}
        {{- with .Values.backend.extraVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.backend.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.backend.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.backend.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
